src/Entity/Document.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DocumentRepository")
 */
class Document
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cerfa;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $convention_financiere;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $eval_entreprise;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lm;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lettre_demission;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $eval_entretien;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $CV;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCerfa(): ?string
    {
        return $this->cerfa;
    }

    public function setCerfa(string $cerfa): self
    {
        $this->cerfa = $cerfa;

        return $this;
    }

    public function getConventionFinanciere(): ?string
    {
        return $this->convention_financiere;
    }

    public function setConventionFinanciere(?string $convention_financiere): self
    {
        $this->convention_financiere = $convention_financiere;

        return $this;
    }

    public function getEvalEntreprise(): ?string
    {
        return $this->eval_entreprise;
    }

    public function setEvalEntreprise(?string $eval_entreprise): self
    {
        $this->eval_entreprise = $eval_entreprise;

        return $this;
    }

    public function getLm(): ?string
    {
        return $this->lm;
    }

    public function setLm(?string $lm): self
    {
        $this->lm = $lm;

        return $this;
    }

    public function getLettreDemission(): ?string
    {
        return $this->lettre_demission;
    }

    public function setLettreDemission(?string $lettre_demission): self
    {
        $this->lettre_demission = $lettre_demission;

        return $this;
    }

    public function getEvalEntretien(): ?string
    {
        return $this->eval_entretien;
    }

    public function setEvalEntretien(?string $eval_entretien): self
    {
        $this->eval_entretien = $eval_entretien;

        return $this;
    }

    public function getCV(): ?string
    {
        return $this->CV;
    }

    public function setCV(?string $CV): self
    {
        $this->CV = $CV;

        return $this;
    }
}

src/Entity/Stagiaire.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StagiaireRepository")
 */
class Stagiaire
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mail;

    /**
     * @ORM\Column(type="date")
     */
    private $date_naissance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lieu_naissance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nationalite;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numero_secu;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $situation_familiale;

    /**
     * @ORM\Column(type="boolean")
     */
    private $permis;

    /**
     * @ORM\Column(type="boolean")
     */
    private $vehicule;

    /**
     * @ORM\Column(type="boolean")
     */
    private $travailleur_handicape;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\DemandeurEmploi", cascade={"persist", "remove"})
     */
    private $id_demandeur_emploi;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\NiveauScolaire", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_niveau_scolaire;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Statut")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_statut;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Entreprise", inversedBy="stagiaires")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_entreprise;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ville", inversedBy="stagiaires")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_ville;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Document", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_document;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $num_rue;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $rue;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Session", mappedBy="stagiaires")
     */
    private $sessions;

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getLieuNaissance(): ?string
    {
        return $this->lieu_naissance;
    }

    public function setLieuNaissance(string $lieu_naissance): self
    {
        $this->lieu_naissance = $lieu_naissance;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(string $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    public function getNumeroSecu(): ?string
    {
        return $this->numero_secu;
    }

    public function setNumeroSecu(string $numero_secu): self
    {
        $this->numero_secu = $numero_secu;

        return $this;
    }

    public function getSituationFamiliale(): ?string
    {
        return $this->situation_familiale;
    }

    public function setSituationFamiliale(string $situation_familiale): self
    {
        $this->situation_familiale = $situation_familiale;

        return $this;
    }

    public function getPermis(): ?bool
    {
        return $this->permis;
    }

    public function setPermis(bool $permis): self
    {
        $this->permis = $permis;

        return $this;
    }

    public function getVehicule(): ?bool
    {
        return $this->vehicule;
    }

    public function setVehicule(bool $vehicule): self
    {
        $this->vehicule = $vehicule;

        return $this;
    }

    public function getTravailleurHandicape(): ?bool
    {
        return $this->travailleur_handicape;
    }

    public function setTravailleurHandicape(bool $travailleur_handicape): self
    {
        $this->travailleur_handicape = $travailleur_handicape;

        return $this;
    }

    public function getIdDemandeurEmploi(): ?DemandeurEmploi
    {
        return $this->id_demandeur_emploi;
    }

    public function setIdDemandeurEmploi(?DemandeurEmploi $id_demandeur_emploi): self
    {
        $this->id_demandeur_emploi = $id_demandeur_emploi;

        return $this;
    }

    public function getIdNiveauScolaire(): ?NiveauScolaire
    {
        return $this->id_niveau_scolaire;
    }

    public function setIdNiveauScolaire(NiveauScolaire $id_niveau_scolaire): self
    {
        $this->id_niveau_scolaire = $id_niveau_scolaire;

        return $this;
    }

    public function getIdStatut(): ?Statut
    {
        return $this->id_statut;
    }

    public function setIdStatut(?Statut $id_statut): self
    {
        $this->id_statut = $id_statut;

        return $this;
    }

    public function getIdEntreprise(): ?Entreprise
    {
        return $this->id_entreprise;
    }

    public function setIdEntreprise(?Entreprise $id_entreprise): self
    {
        $this->id_entreprise = $id_entreprise;

        return $this;
    }

    public function getIdVille(): ?Ville
    {
        return $this->id_ville;
    }

    public function setIdVille(?Ville $id_ville): self
    {
        $this->id_ville = $id_ville;

        return $this;
    }

    public function getIdDocument(): ?Document
    {
        return $this->id_document;
    }

    public function setIdDocument(Document $id_document): self
    {
        $this->id_document = $id_document;

        return $this;
    }

    public function getNumRue(): ?string
    {
        return $this->num_rue;
    }

    public function setNumRue(string $num_rue): self
    {
        $this->num_rue = $num_rue;

        return $this;
    }

    public function getRue(): ?string
    {
        return $this->rue;
    }

    public function setRue(string $rue): self
    {
        $this->rue = $rue;

        return $this;
    }

    /**
     * @return Collection|Session[]
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): self
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions[] = $session;
            $session->addStagiaire($this);
        }

        return $this;
    }

    public function removeSession(Session $session): self
    {
        if ($this->sessions->contains($session)) {
            $this->sessions->removeElement($session);
            $session->removeStagiaire($this);
        }

        return $this;
    }
}

src/Entity/Ville.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VilleRepository")
 */
class Ville
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code_postal;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Entreprise", mappedBy="id_ville")
     */
    private $entreprises;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Stagiaire", mappedBy="id_ville")
     */
    private $stagiaires;

    public function __construct()
    {
        $this->entreprises = new ArrayCollection();
        $this->stagiaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    /**
     * @return Collection|Entreprise[]
     */
    public function getEntreprises(): Collection
    {
        return $this->entreprises;
    }

    public function addEntreprise(Entreprise $entreprise): self
    {
        if (!$this->entreprises->contains($entreprise)) {
            $this->entreprises[] = $entreprise;
            $entreprise->setIdVille($this);
        }

        return $this;
    }

    public function removeEntreprise(Entreprise $entreprise): self
    {
        if ($this->entreprises->contains($entreprise)) {
            $this->entreprises->removeElement($entreprise);
            // set the owning side to null (unless already changed)
            if ($entreprise->getIdVille() === $this) {
                $entreprise->setIdVille(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Stagiaire[]
     */
    public function getStagiaires(): Collection
    {
        return $this->stagiaires;
    }

    public function addStagiaire(Stagiaire $stagiaire): self
    {
        if (!$this->stagiaires->contains($stagiaire)) {
            $this->stagiaires[] = $stagiaire;
            $stagiaire->setIdVille($this);
        }

        return $this;
    }

    public function removeStagiaire(Stagiaire $stagiaire): self
    {
        if ($this->stagiaires->contains($stagiaire)) {
            $this->stagiaires->removeElement($stagiaire);
            // set the owning side to null (unless already changed)
            if ($stagiaire->getIdVille() === $this) {
                $stagiaire->setIdVille(null);
            }
        }

        return $this;
    }
}

src/Form/StagiaireType.php
<?php

namespace App\Form;

use App\Entity\Stagiaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StagiaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom',TextType::class,['label'=>'Nom'])
            ->add('prenom',TextType::class,['label'=>'Prénom'])
            ->add('telephone',TelType::class,['label'=>'N° téléphone'])
            ->add('mail',EmailType::class,['label'=>'Adresse mail'])
            ->add('date_naissance',DateType::class,[
                'label'=>'Date de naissance',
                'widget'=>'single_text'
                ])
            ->add('lieu_naissance',TextType::class,['label'=>'Lieu de naissance'])
            ->add('nationalite',TextType::class,['label'=>'Nationalité'])
            ->add('numero_secu',IntegerType::class,['label'=>'N° sécurité social'])
            ->add('situation_familiale',TextType::class,['label'=>'Situation familiale'])
            ->add('permis',ChoiceType::class,[
                'label'=>'Permis',
                'choices'=>
                    [
                    'Oui'=>true,
                    'Non'=>false
                    ],
                'expanded'=>true,
                'multiple'=>false
                ])
            ->add('vehicule',ChoiceType::class,[
                'label'=>'Véhicule',
                'choices'=>
                    [
                    'Oui'=>true,
                    'Non'=>false
                    ],
                'expanded'=>true,
                'multiple'=>false
                ])
            ->add('travailleur_handicape',ChoiceType::class,[
                'label'=>'Travailleur handicapé',
                'choices'=>
                    [
                    'Oui'=>true,
                    'Non'=>false
                    ],
                'expanded'=>true,
                'multiple'=>false
                ])
            ->add('num_rue',TextType::class,['label'=>'N°'])
            ->add('rue',TextType::class,['label'=>'Nom'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Stagiaire::class,
        ]);
    }
}

templates/stagiaire/_delete_form.html.twig
<form method="post" action="{{ path('stagiaire_delete', {'id': stagiaire.id}) }}" onsubmit="return confirm('Est-vous sûr de supprimer cet étudiant ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ stagiaire.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/stagiaire/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() ~ " - Editier Etudiant" }}{% endblock %}
{% block body %}
{{ include('stagiaire/_form.html.twig') }}
{% endblock %}

{% block javascripts %}
<script type="text/javascript">
//Dans le cas où un étudiant n'a qu'une et une seule session
if($('#list_session div').length==1)
    $('#list_session div button').remove();

//Bouton Valider de la modal de session
$('#validationSession').click(function()
    {
    let sessionId=$('#session_id option:selected').val().trim();
    if(sessionId!="")
        {
        $.ajax({
            url:"{{ path('add_session',{'stagiaire':stagiaire.id,'session':'sessionId'}) }}".replace('sessionId',sessionId),
            type:"POST",
            dataType:"html",
            data:{},
            async:true,
            success:function(data)
                {
                $('#list_session').html(data);
                //Si il y a qu'une session
                if($('#list_session div').length==1)
                    $('#list_session div button').remove();
                }
            });
        }
    });
//Bouton de suppresion d'une session
function suppressionSession(id)
    {
    if(confirm("Est-vous sûr d'enlever cette session ?"))
        {
        $.ajax({
            url:"{{ path('delete_session',{'stagiaire':stagiaire.id,'session':'sessionId'}) }}".replace('sessionId',id),
            type:"POST",
            dataType:"html",
            data:{},
            async:true,
            success:function(data)
                {
                $('#list_session').html(data);
                //Si il y a qu'une session
                if($('#list_session div').length==1)
                    $('#list_session div button').remove();
                }
            });
        }
    }
</script>
{% endblock %}

templates/stagiaire/show.html.twig
{% extends 'base.html.twig' %}

{% set demandeEmploi=stagiaire.idDemandeurEmploi %}
{% set niveauScolaire=stagiaire.idNiveauScolaire %}
{% set document=stagiaire.idDocument %}

{% block title %}{{ parent() ~ " - Affichage Etudiant" }}{% endblock %}

{% block body %}
<div class="container-fluid">
  <div class="d-flex">
      <a href="{{ path('stagiaire_index') }}" class="btn btn-primary">Retour à la liste</a>
      <a href="{{ path('stagiaire_edit', {'id': stagiaire.id}) }}" class="btn btn-warning ml-2 mr-2">Editer</a>
      {{ include('stagiaire/_delete_form.html.twig') }}
  </div>
  <div class="row">
      <!--Panneau données-->
      <nav class="col-auto">
          <h3 class="text-light">Liste des données</h3>
          <ul class="d-flex flex-column">
              <li>
                  <button type="button" class="btn btn-primary mb-1 text-light btnNavShow" id="identite">Identité</button>
              </li>
              <li>
                  <button type="button" class="btn btn-outline-info mb-1 text-light btnNavShow" id="informationsComplementaire">Informations complémentaires</button>
              </li>
              <li>
                  <button type="button" class="btn btn-outline-info mb-1 text-light btnNavShow" id="niveauScolaire">Niveau scolaire</button>
              </li>
              {% if demandeEmploi is not null %}
                  <li>
                      <button type="button" class="btn btn-outline-info mb-1 text-light btnNavShow" id="demandeEmploi">Demandeur d'emploi</button>
                  </li>
              {% endif %}
              <li>
                  <button type="button" class="btn btn-outline-info text-light btnNavShow" id="document">Documents</button>
              </li>
          </ul>
      </nav>
      <!--Données-->
      <div class="col-auto mb-3">
          <!--Show identite-->
          <div id="identiteShow" class="show">
              <h3 class="text-light">Identité</h3>
              <p class="text-light m-0">
                  <strong class="text-white">Nom: </strong>
                  {{ stagiaire.nom }}
              </p>
              <p class="text-light m-0">
                  <strong class="text-white">Prénom: </strong>
                  {{ stagiaire.prenom }}
              </p>
              <p class="text-light m-0">
                  <strong class="text-white">Nationalité: </strong>
                  {{ stagiaire.nationalite }}
              </p>
              <p class="text-light m-0">
                  <strong class="text-white">Date de naissance: </strong>
                  {{ stagiaire.lieuNaissance }}
              </p>
              <p class="text-light m-0">
                  <strong class="text-white">Lieu de naissance: </strong>
                  {{ stagiaire.dateNaissance|date('d/m/Y') }}
              </p>
          </div>
          <!--Show informations complémentaires-->
          <div id="informationsComplementaireShow" class="show">
              <h3 class="text-light">Information complémentaire</h3>
              <p class="text-light m-0">
                  <strong class="text-white">Mail: </strong>
                  {{ stagiaire.mail }}
              </p>
              <p class="text-light m-0">
                  <strong class="text-white">Téléphone: </strong>
                  {{ stagiaire.telephone }}
              </p>
              <p class="text-light m-0">
                  <strong class="text-white">Permis: </strong>
                  {{ stagiaire.permis ? 'oui' : 'non' }}
              </p>
              <p class="text-light m-0">
                  <strong class="text-white">Véhicule: </strong>
                  {{ stagiaire.vehicule ? 'oui' : 'non' }}
              </p>
              <p class="text-light m-0">
                  <strong class="text-white">Travailleur handicapé: </strong>
                  {{ stagiaire.travailleurHandicape ? 'oui' : 'non' }}
              </p>
              <p class="text-light m-0">
                  <strong class="text-white">Numéro de sécurité social: </strong>
                  {{ stagiaire.numeroSecu }}
              </p>
              <p class="text-light m-0">
                  <strong class="text-white">Situation familiale: </strong>
                  {{ stagiaire.situationFamiliale }}
              </p>
              <p class="text-light m-0">
                  <strong class="text-white">Adresse: </strong>
                  {{ stagiaire.numRue~" "~stagiaire.rue~" "~stagiaire.idVille.nom~" "~stagiaire.idVille.codePostal }}
              </p>
          </div>
          <!--Show niveau scolaire-->
          <div id="niveauScolaireShow" class="show">
              <h3 class="text-light">Niveau scolaire</h3>
              <div class="d-flex">
                  <div class=" w-50">
                      <h4 class="text-light mb-0">Dernière classe</h4>
                      <p class="text-light m-0">
                          <strong class="text-white">Nom: </strong>
                          {{ niveauScolaire.derniereClasse }}
                      </p>
                      <p class="text-light m-0">
                          <strong class="text-white">Date: </strong>
                          {{ niveauScolaire.dateDerniereClasse|date('d/m/Y') }}
                      </p>
                      <h4 class="text-light mb-0 mt-2">Dernier diplôme</h4>
                      <p class="text-light m-0">
                          <strong class="text-white">Nom: </strong>
                          {{ niveauScolaire.dernierDiplome }}
                      </p>
                      <p class="text-light m-0">
                          <strong class="text-white">Date: </strong>
                          {{ niveauScolaire.dateDernierDiplome|date('d/m/Y') }}
                      </p>
                  </div>
                  <div class="w-50 ml-3">
                      <h4 class="text-light mb-0">Dernier emploi</h4>
                      <p class="text-light m-0">
                          <strong class="text-white">Nom: </strong>
                          {{ niveauScolaire.dernierEmploi }}
                      </p>
                      <p class="text-light m-0">
                          <strong class="text-white">Date: </strong>
                          {{ niveauScolaire.dateDernierEmploi|date('d/m/Y') }}
                      </p>
                      <h4 class="text-light mb-0 mt-2">Employeur</h4>
                      <p class="text-light m-0">
                          <strong class="text-white">Nom: </strong>
                          {{ niveauScolaire.nomDernierEmployeur }}
                      </p>
                      <p class="text-light m-0">
                          <strong class="text-white">Adresse: </strong>
                          {{ niveauScolaire.adresseDernierEmployeur }}
                      </p>
                  </div>
              </div>
              <h4 class="text-light mb-0 mt-2">Formation</h4>
              <div class="d-flex">
                  <p class="text-light m-0 w-50">
                      <strong class="text-white">Statut: </strong>
                      {{ stagiaire.idStatut.libelle }}
                  </p>
                  <p class="m-0 ml-3 w-50">
                      <strong class="text-white">Entreprise: </strong>
                      <a href="{{ path('entreprise_show',{'id':stagiaire.idEntreprise.id}) }}" target="_blank" class="text-body">{{ stagiaire.idEntreprise.nom }}</a>
                  </p>
              </div>
          </div>
          <!--Show demandeur d'emploi-->
          {% if demandeEmploi is not null %}
              <div id="demandeEmploiShow" class="show">
                  <h3 class="text-light">Demandeur d'emploi</h3>
                  <div>
                      <p class="text-light m-0">
                          <strong class="text-white">Date d'inscription: </strong>
                          {{ demandeEmploi.dateInscription }}
                      </p>
                      <p class="text-light m-0">
                          <strong class="text-white">Identifiant: </strong>
                          {{ demandeEmploi.identifiant }}
                      </p>
                      <p class="text-light m-0">
                          <strong class="text-white">Ville du pôle emploi: </strong>
                          {{ demandeEmploi.villePoleEmploi }}
                      </p>
                      <p class="text-light m-0">
                          <strong class="text-white">Antenne mission local: </strong>
                          {{ demandeEmploi.antenneMissionLocale }}
                      </p>
                      <p class="text-light m-0">
                          <strong class="text-white">Nom du conseiller: </strong>
                          {{ demandeEmploi.nomConseiller }}
                      </p>
                      <p class="text-light m-0">
                          <strong class="text-white">CIVIS: </strong>
                          {{ demandeEmploi.CIVIS ? 'oui' : 'non' }}
                      </p>
                  </div>
              </div>
          {% endif %}
          <!--Show documents-->
          <div id="documentShow" class="show">
              <h3 class="text-light">Document</h3>
              <p><a href="{{ asset(document.cerfa) }}" target="_blank" class="btn btn-info">cerfa - visualiser</a></p>
              <p><a href="{{ asset(document.conventionFinanciere) }}" target="_blank" class="btn btn-info">Convention financière - visualiser</a></p>
              <p><a href="{{ asset(document.lm) }}" target="_blank" class="btn btn-info">Lettre de motivation - visualiser</a></p>
              <p><a href="{{ asset(document.cv) }}" target="_blank" class="btn btn-info">CV - visualiser</a></p>
              <p><a href="{{ asset(document.lettreDemission) }}" target="_blank" class="btn btn-info">Lettre de démission - visualiser</a></p>
              <p><a href="{{ asset(document.evalEntretien) }}" target="_blank" class="btn btn-info">Evaluation entreprise - visualiser</a></p>
              <p><a href="{{ asset(document.evalEntreprise) }}" target="_blank" class="btn btn-info">Evaluation entretien - visualiser</a></p>
          </div>
      </div>
      <!--Sessions-->
			<div class="d-flex flex-column col-auto mb-3">
          <h4 class="text-light m-0">Sessions</h4>
          {% for session in stagiaire.sessions %}
              <a href="{{ path('session_show',{'id':session.id}) }}" target="_blank" class="text-body">{{ session.nom }}</a>
          {% endfor %}
			</div>
      <!--Allocations-->
      {% if demandeEmploi is not null and demandeEmploi.idAllocation|length > 0 %}
        <div class="col-auto">
            <h4 class="text-light m-0">Allocation</h4>
            {% for allocation in demandeEmploi.idAllocation %}
              <div class="">
                <strong class="text-white">{{ allocation.libelle }}</strong>
                <p class="text-light m-0">{{ allocation.description }}</p>
              </div>
            {% endfor %}
        </div>
      {% endif %}
  </div>
</div>
{% endblock %}

{% block javascripts %}
<script type="text/javascript">
$('.show').hide();
$('#identiteShow').show();

$('.btnNavShow').click(function()
    {//Changement de formulaire
    $('.show').hide();
    $('#'+$(this).attr('id')+'Show').show();
    //Changement de classe du bouton
    $('button.btnNavShow.btn-primary').removeClass('btn-primary').addClass('btn-outline-info');
    $(this).removeClass('btn-outline-info').addClass('btn-primary');
    });
</script>
{% endblock %}