src/Entity/Enseigner.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EnseignerRepository")
 */
class Enseigner
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Session", inversedBy="enseigners")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_session;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Module")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_module;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Formateur", inversedBy="enseigners")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_formateur;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdSession(): ?Session
    {
        return $this->id_session;
    }

    public function setIdSession(?Session $id_session): self
    {
        $this->id_session = $id_session;

        return $this;
    }

    public function getIdModule(): ?Module
    {
        return $this->id_module;
    }

    public function setIdModule(?Module $id_module): self
    {
        $this->id_module = $id_module;

        return $this;
    }

    public function getIdFormateur(): ?Formateur
    {
        return $this->id_formateur;
    }

    public function setIdFormateur(?Formateur $id_formateur): self
    {
        $this->id_formateur = $id_formateur;

        return $this;
    }
}

src/Entity/Session.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SessionRepository")
 */
class Session
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Formation")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_formation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="date")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="date")
     */
    private $date_fin;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Enseigner", mappedBy="id_session", orphanRemoval=true)
     */
    private $enseigners;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Stagiaire", inversedBy="sessions")
     */
    private $stagiaires;

    public function __construct()
    {
        $this->enseigners = new ArrayCollection();
        $this->stagiaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdFormation(): ?Formation
    {
        return $this->id_formation;
    }

    public function setIdFormation(?Formation $id_formation): self
    {
        $this->id_formation = $id_formation;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    /**
     * @return Collection|Enseigner[]
     */
    public function getEnseigners(): Collection
    {
        return $this->enseigners;
    }

    public function addEnseigner(Enseigner $enseigner): self
    {
        if (!$this->enseigners->contains($enseigner)) {
            $this->enseigners[] = $enseigner;
            $enseigner->setIdSession($this);
        }

        return $this;
    }

    public function removeEnseigner(Enseigner $enseigner): self
    {
        if ($this->enseigners->contains($enseigner)) {
            $this->enseigners->removeElement($enseigner);
            // set the owning side to null (unless already changed)
            if ($enseigner->getIdSession() === $this) {
                $enseigner->setIdSession(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Stagiaire[]
     */
    public function getStagiaires(): Collection
    {
        return $this->stagiaires;
    }

    public function addStagiaire(Stagiaire $stagiaire): self
    {
        if (!$this->stagiaires->contains($stagiaire)) {
            $this->stagiaires[] = $stagiaire;
        }

        return $this;
    }

    public function removeStagiaire(Stagiaire $stagiaire): self
    {
        if ($this->stagiaires->contains($stagiaire)) {
            $this->stagiaires->removeElement($stagiaire);
        }

        return $this;
    }
}

src/Form/SessionType.php
<?php

namespace App\Form;

use App\Entity\Session;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SessionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom',TextType::class,['label'=>'Nom'])
            ->add('date_debut',DateType::class,['label'=>'Date de début','widget'=>'single_text'])
            ->add('date_fin',DateType::class,['label'=>'Date de fin','widget'=>'single_text'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Session::class,
        ]);
    }
}

src/Controller/SessionController.php
<?php

namespace App\Controller;

use App\Entity\Session;
use App\Entity\Enseigner;
use App\Form\SessionType;
use App\Repository\SessionRepository;
use App\Repository\FormationRepository;
use App\Repository\FormateurRepository;
use App\Repository\StagiaireRepository;
use App\Repository\ModuleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/session")
 */
class SessionController extends AbstractController
    {
    /**
     * @Route("/index/{page}", name="session_index")
     */
    public function index(SessionRepository $sessionRepository,int $page=1): Response
        {/*Calcul le nombre de pages par le nombre total de sessions divisé par 10
        Cette variable doit rester en float pour le template twig correspondant*/
        $pages=count($sessionRepository->findAll())/10;
        //Vérifie que la valeur de l'argument $page est bien compris entre 1 et $pages
        $page=($page>=1&&$page<=(int)$pages)?$page:1;
        //Récupére jusqu'a 10 sessions, et selon la page
        $sessions=$sessionRepository->findBy([],null,10,($page*10)-10);
        /*Si il y a au moins 4 pages qui précède la page actuelle
        Alors la pagination commence avec le numéro de la page actuelle - 4
        Sinon, elle commence à la page 1*/
        $pageDebut=($page-4>=1)?$page-4:1;
        /*Si il y a plus de 4 pages qui suit la page actuelle
        Alors la pagination s'arrête avec le numéro de la page actuelle + 4
        Sinon, elle s'arrête à la dernière page*/
        $pageFin=($page+4<=(int)$pages)?$page+4:(int)$pages;
        return $this->render('session/index.html.twig', [
            'controller_name'=>'session',
            'sessions'=>$sessions,
            'pageDebut'=>$pageDebut,
            'pageFin'=>$pageFin,
            'page'=>$page,
            'pages'=>$pages
            ]);
        }

    /**
     * @Route("/new", name="session_new")
     */
    public function new(Request $request,FormationRepository $formationRepository,FormateurRepository $formateurRepository,ModuleRepository $moduleRepository): Response
        {
        $session = new Session();
        $form = $this->createForm(SessionType::class, $session);
        $form->handleRequest($request);
        //Si il y a une formation de passer par le formulaire et qui a un attribut id
        $formation=($request->get('formation')&&$request->get('formation')['id']) ? $formationRepository->find($request->get('formation')['id']) : null;
        //Si  la formation existe en base de données et que pour la session, la date de début soit inférieur à la date de fin
        if($form->isSubmitted()&&$form->isValid()&&!is_null($formation)&&$session->getDateDebut()<$session->getDateFin()) 
            {
            $entityManager = $this->getDoctrine()->getManager();
            //Ajout de la formation à l'objet Session
            $session->setIdFormation($formation);
            //Parcour de la liste Enseigner
            for($i=0;$request->get("enseigner_".$i);$i++)
                {//Récupération des valeurs pour un objet Enseigner
                $dataEnseigner=$request->get("enseigner_".$i);
                //Création d'un objet Enseigner et persistance de celui
                $enseigner=new Enseigner();
                $enseigner->setIdSession($session);
                $enseigner->setIdModule($moduleRepository->find($dataEnseigner['module']));
                $enseigner->setIdFormateur($formateurRepository->find($dataEnseigner['formateur']));
                $entityManager->persist($enseigner);
                }
            //Persistance de la session et sauvegarde en base de données
            $entityManager->persist($session);
            $entityManager->flush();
            //Redirection vers cette session
            return $this->redirectToRoute('session_show', ['id' => $session->getId()]);
            }

        return $this->render('session/new.html.twig', [
            'controller_name'=>'session',
            'session' => $session,
            'formations'=>$formationRepository->findAll(),
            'formateurs'=>$formateurRepository->findAll(),
            'form' => $form->createView(),
            ]);
        }

    /**
     * @Route("/show/{id}", name="session_show", methods={"GET"})
     */
    public function show(Session $session): Response
        {
        return $this->render('session/show.html.twig', [
            'controller_name'=>'session',
            'session' => $session,
            ]);
        }

    /**
     * @Route("/edit/{id}", name="session_edit")
     */
    public function edit(Request $request, Session $session,FormationRepository $formationRepository,FormateurRepository $formateurRepository): Response
        {
        $form = $this->createForm(SessionType::class, $session);
        $form->handleRequest($request);
        //Si pour la session, la date de début est inférieur à la date de fin
        if ($form->isSubmitted()&&$form->isValid()&&$session->getDateDebut()<$session->getDateFin()) 
            {
            $this->getDoctrine()->getManager()->flush();
            return $this->redirectToRoute('session_show', ['id' => $session->getId()]);
            }   

        return $this->render('session/edit.html.twig', [
            'controller_name'=>'session',
            'session' => $session,
            'formations'=>$formationRepository->findAll(),
            'formateurs'=>$formateurRepository->findAll(),
            'form' => $form->createView(),
            ]);
        }

    /**
     * @Route("/delete/{id}", name="session_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Session $session): Response
        {
        if ($this->isCsrfTokenValid('delete'.$session->getId(), $request->request->get('_token')))
            {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($session);
            $entityManager->flush();
            }

        return $this->redirectToRoute('session_index');
        }
    }

templates/session/_delete_form.html.twig
<form method="post" action="{{ path('session_delete', {'id': session.id}) }}" onsubmit="return confirm('Est-vous sûr de supprimer cette session ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ session.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/session/_form.html.twig
{{ form_start(form,{'attr':{'class':'container-fluid'}}) }}
<div class="d-flex">
	<a href="{{ path('session_index') }}" class="btn btn-primary">Retour à la liste</a>
	{% if session.id is not null %}
        <a href="{{ path('session_show', {'id': session.id}) }}" class="btn btn-primary ml-2">Afficher</a>
    {% endif %}
	<button class="btn btn-success ml-2">{{ button_label|default('Sauvegarder') }}</button>
</div>
<div class="row">
	<div class="col-auto mb-3">
		<h4 class="text-light">Session{% if session.id is not null %} (<a class="text-body" href="{{ path('formation_show',{'id':session.idFormation.id}) }}" target="_blank">{{ session.idFormation.libelle }}</a>){% endif %}</h4>
		<div class="input-group mb-1">
			<div class="input-group-prepend">{{ form_label(form.nom,'',{'label_attr':{'class':'input-group-text'}}) }}</div>
			{{ form_widget(form.nom,{'attr':{'class':'form-control'}}) }}
		</div>
		<div class="input-group mb-1">
			<div class="input-group-prepend">{{ form_label(form.date_debut,'',{'label_attr':{'class':'input-group-text'}}) }}</div>
			{{ form_widget(form.date_debut,{'attr':{'class':'form-control'}}) }}
		</div>
		<div class="input-group mb-1">
			<div class="input-group-prepend">{{ form_label(form.date_fin,'',{'label_attr':{'class':'input-group-text'}}) }}</div>
			{{ form_widget(form.date_fin,{'attr':{'class':'form-control'}}) }}
		</div>
		{#Lors de la création d'une session#}
		{% if session.id is null %}
			<div class="input-group">
				<div class="input-group-prepend"><label for="formation_id" class="required input-group-text">Formation</label></div>
				<select id="formation_id" name="formation[id]" class="form-control">
					{% for formation in formations %}
						<option value="{{ formation.id }}">{{ formation.libelle }}</option>
					{% endfor %}
				</select>
			</div>
		{% endif %}
	</div>
	<div class="d-flex flex-column col-auto">
		<div class="d-flex align-items-center">
			<h4 class="text-light m-0">Enseigner</h4>
			<button type="button" class="btn btn-primary ml-1" id="btnModalEnseigner" data-toggle="modal" data-target="#modalEnseigner">Ajouter</button>
		</div>
		<div id="list_enseigner">
			{% for enseigner in session.enseigners %}
          <div class="d-flex align-items-center mt-1">
          	<button type="button" class="btn btn-danger" onclick="suppressionEnseigner({{ enseigner.id }})">Supprimer</button>
          	<button type="button" class="btn btn-warning ml-1 mr-1" data-toggle="modal" data-target="#modalEnseigner" onclick="editionEnseigner({{ enseigner.id }})">Editer</button>
          	<p class="text-light m-0">{{ enseigner.idModule.libelle }}</p>
          </div>
      {% endfor %}
		</div>
	</div>
</div>
{{ form_end(form) }}

<!--Modal-->
<div class="modal fade" id="modalEnseigner" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Enseigner</h5>
            </div>
            <div class="modal-body bg-secondary w-100" id="modal-body-enseigner">
                <p class="text-center text-light m-0">Chargement du formulaire, veuillez patientez ....</p>
            </div>
            <div class="modal-footer">
                <button id="validationEnseigner" class="btn btn-success" data-dismiss="modal">Valider</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
            </div>
        </div>
    </div>
</div>

templates/session/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() ~ " - Editier Session" }}{% endblock %}

{% block body %}
{{ include('session/_form.html.twig') }}
{% endblock %}

{% block javascripts %}
{{ parent() }}
<script type="text/javascript">
//Bouton d'ajout de module
$('#btnModalEnseigner').click(function()
    {
    $('#validationEnseigner').attr('onclick','ajaxEnseigner()');
    $.ajax({
        url:"{{ path('enseigner_form',{'idFormation': session.idFormation.id}) }}",
        type:"POST",
        dataType:"html",
        data:{},
        async:true,
        success:function(data)
            {
            $('#modal-body-enseigner').html(data);
            }
        });
    });
//Bouton de suppresion d'un module
function suppressionEnseigner(id)
    {
    if(confirm('Est-vous sûr de supprimer ce module ?'))
        $.ajax({
            url:"{{ path('enseigner_delete',{'id':'id'}) }}".replace('id',id),
            type:"POST",
            dataType:"html",
            data:{},
            async:true,
            success:function(data)
                {
                $('#list_enseigner').html(data);
                }
            });
    }
//Bouton de modification d'un module
function editionEnseigner(id)
    {
    $('#validationEnseigner').attr('onclick','ajaxEnseigner('+id+')');
    $.ajax({
        url:"{{ path('enseigner_form',{'idFormation': session.idFormation.id ,'idEnseigner':'id'}) }}".replace('id',id),
        type:"POST",
        dataType:"html",
        data:{},
        async:true,
        success:function(data)
            {
            $('#modal-body-enseigner').html(data);
            }
        });
    }
//Bouton qui rajoute ou modifie un module
function ajaxEnseigner(id)
    {
    if(id)
        var path="{{ path('enseigner_edit',{'id':'id'}) }}".replace('id',id);
    else
        var path="{{ path('enseigner_new',{'session':session.id}) }}";
    $.ajax({
        url:path,
        type:"POST",
        dataType:"html",
        data:{'module':$('#enseigner_module_id').val(),'formateur':$('#enseigner_formateur_id').val(),'session':'{{ session.id }}'},
        async:true,
        success:function(data)
            {
            $('#list_enseigner').html(data);
            }
        });
    }
</script>
{% endblock %}

templates/session/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() ~ " - Sessions" }}{% endblock %}

{% block body %}
<div class="container-fluid">
  <h3 class="text-light">Liste des sessions</h3>
  <a href="{{ path('session_new') }}" class="btn btn-primary mb-2">Nouvelle session</a>
  {% if pages > 1 %}
      <nav class="d-flex">
          <ul class="pagination">
              {% if page > 1 %}
                  <li class="page-item"><a class="page-link" href="{{ path('session_index', {'page': 1}) }}">Début</a></li>
                  <li class="page-item"><a class="page-link" href="{{ path('session_index', {'page': page-1}) }}">Précédent</a></li>
              {% endif %}
              {% for i in range(pageDebut,pageFin) %}
                  <li class="page-item">
                      {% if page == i %}
                          <a class="page-link bg-primary text-light">{{ i }}</a>
                      {% else %}
                          <a class="page-link" href="{{ path('session_index', {'page': i}) }}">{{ i }}</a>
                      {% endif %}
                  </li>
              {% endfor %}
              {% if page < pages %}
                  <li class="page-item"><a class="page-link" href="{{ path('session_index', {'page': page+1}) }}">Suivant</a></li>
                  <li class="page-item"><a class="page-link" href="{{ path('session_index', {'page': pages}) }}">Fin</a></li>
              {% endif %}
          </ul>
      </nav>
  {% endif %}
  <div class="table-responsive">
    <table class="table table-dark table-striped table-hover table-bordered mb-0">
        <thead>
            <tr>
                <th class="text-truncate">Nom</th>
                <th class="text-truncate">Date de début</th>
                <th class="text-truncate">Date de fin</th>
                <th class="w-25">Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for session in sessions %}
            <tr>
                <td class="align-middle text-truncate">{{ session.nom }}</td>
                <td class="align-middle text-truncate">{{ session.dateDebut ? session.dateDebut|date('Y-m-d') : '' }}</td>
                <td class="align-middle text-truncate">{{ session.dateFin ? session.dateFin|date('Y-m-d') : '' }}</td>
                <td>
                  <div class="d-flex">
                    <a href="{{ path('session_show', {'id': session.id}) }}" class="btn btn-primary">Afficher</a>
                    <a href="{{ path('session_edit', {'id': session.id}) }}" class="btn btn-warning ml-2 mr-2">Editer</a>
                    {{ include('session/_delete_form.html.twig') }}
                  </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Aucune session</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
  </div>
</div>
{% endblock %}

templates/session/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() ~ " - Nouvelle Session" }}{% endblock %}

{% block body %}
{{ include('session/_form.html.twig') }}
{% endblock %}

{% block javascripts %}
{{ parent() }}
<script type="text/javascript">
//Changement de formation, suppression des enseignements
$('#formation_id').change(function()
    {
    $('#list_enseigner').children().remove();
    });
//Bouton d'ajout d'un enseignement
$('#btnModalEnseigner').click(function()
    {
    $.ajax({
        url:"{{ path('enseigner_form',{'idFormation':'idFormation'}) }}".replace('idFormation',$('#formation_id option:selected').val()),
        type:"POST",
        dataType:"html",
        data:{},
        async:true,
        success:function(data)
            {
            $('#modal-body-enseigner').html(data);
            },
        error: function(jqXHR, textStatus, errorThrown)
            {
            $('#modal-body-enseigner p').text("Veuillez saisir une formation.")
            }
        });
    });
//Bouton Valider de la modal
$('#validationEnseigner').click(function()
    {//Récupération des valeurs
    let moduleId=$('#enseigner_module_id option:selected');
    let formateurId=$('#enseigner_formateur_id option:selected');
    //Vérification des valeurs
    if(moduleId.val().trim()!=""&&formateurId.val().trim()!="")
        {//Calcul le nombre d'enseignement déjà crée
        let length=$('#list_enseigner div').length;
        //Ajout de l'enseignement en html
        $('#list_enseigner').append(
            '<div id="enseigner_'+length+'" class="d-flex align-items-center mt-1">'+
                '<button type="button" class="btn btn-danger mr-1" onclick="suppressionEnseigner('+length+')">Supprimer</button>'+
                '<p class="text-light m-0">'+moduleId.text()+' (<strong>formateur:</strong> '+formateurId.text()+')</p>'+
                '<input class="module" type="hidden" name="enseigner_'+length+'[module]" value="'+moduleId.val()+'"/>'+
                '<input class="formateur" type="hidden" name="enseigner_'+length+'[formateur]" value="'+formateurId.val()+'"/>'+
            '</div>');
        }
    });
//Bouton de suppresion d'un enseignement
function suppressionEnseigner(id)
    {//Suppression de la div parente du bouton
    $('#enseigner_'+id).remove();
    //Parcours les div situées après la div supprimé
    for(let i=id;i<$('#list_enseigner div').length;i++)
        {//Modification des attributs
        //Div suivante
        $('#enseigner_'+(i+1)).attr('id',"enseigner_"+i);
        //Elements html de la div suivante
        $('#enseigner_'+i+' button').attr('onclick',"suppressionEnseigner("+i+")");
        $('#enseigner_'+i+' .module').attr('name','enseigner_'+i+'[module]');
        $('#enseigner_'+i+' .formateur').attr('name','enseigner_'+i+'[formateur]');
        }
    }
</script>
{% endblock %}

templates/session/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() ~ " - Affichage Session" }}{% endblock %}

{% block body %}
<div class="container-fluid">
  <div class="d-flex">
      <a href="{{ path('session_index') }}" class="btn btn-primary">Retour à la liste</a>
      <a href="{{ path('session_edit', {'id': session.id}) }}" class="btn btn-warning ml-2 mr-2">Editer</a>
      {{ include('session/_delete_form.html.twig') }}
  </div>
  <div class="row">
    <div class="col-auto mb-3">
        <h4 class="text-light">Session (<a class="text-body" href="{{ path('formation_show',{'id':session.idFormation.id}) }}" target="_blank">{{ session.idFormation.libelle }}</a>)</h4>
        <p class="text-light m-0">
            <strong class="text-white">Nom: </strong>
            {{ session.nom }}
        </p>
        <p class="text-light m-0">
            <strong class="text-white">Date de début: </strong>
            {{ session.dateDebut|date('Y-m-d') }}
        </p>
        <p class="text-light m-0">
            <strong class="text-white">Date de fin: </strong>
            {{ session.dateFin|date('Y-m-d') }}
        </p>
    </div>
    <div class="col-auto mb-3">
        <h4 class="text-light">Liste des modules</h4>
        {% for enseigner in session.enseigners %}
            <div class="d-flex align-items-center mt-1">
                <button type="button" class="btn btn-info mr-1" data-toggle="modal" data-target="#modalEnseigner" onclick="detailsEnseigner({{ enseigner.id }})">Détails</button>
                <p class="text-light m-0">{{ enseigner.idModule.libelle }}</p>
            </div>
        {% endfor %}
    </div>
    {% if session.stagiaires|length > 0 %}
        <div class="col-auto">
            <h4 class="text-light">Liste des étudiants</h4>
            {% for stagiaire in session.stagiaires %}
                <a href="{{ path('stagiaire_show',{'id':stagiaire.id}) }}" target="_blank" class="text-body">{{ stagiaire.nom~" "~stagiaire.prenom }}</a>
            {% endfor %}
        </div>
    {% endif %}
  </div>
</div>

<!--Modal-->
<div class="modal fade" id="modalEnseigner" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Enseigner</h5>
            </div>
            <div class="modal-body bg-secondary w-100" id="modal-body-enseigner">
                <p class="text-center text-light m-0">Chargement des données, veuillez patientez ....</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascripts %}
{{ parent() }}
<script type="text/javascript">
function detailsEnseigner(id)
    {
    $.ajax({
        url:"{{ path('enseigner_show',{'id':'id'}) }}".replace('id',id),
        type:"POST",
        dataType:"html",
        data:{},
        async:true,
        success:function(data)
            {
            $('#modal-body-enseigner').html(data);
            }
        });
    }
</script>
{% endblock %}