src/Entity/Rappel.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RappelRepository")
 */
class Rappel
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_rappel;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $valide;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Suivi", inversedBy="rappel")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_suivi;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Contact", inversedBy="rappels")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_contact;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateRappel(): ?\DateTimeInterface
    {
        return $this->date_rappel;
    }

    public function setDateRappel(\DateTimeInterface $date_rappel): self
    {
        $this->date_rappel = $date_rappel;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getValide(): ?bool
    {
        return $this->valide;
    }

    public function setValide(bool $valide): self
    {
        $this->valide = $valide;

        return $this;
    }

    public function getIdSuivi(): ?Suivi
    {
        return $this->id_suivi;
    }

    public function setIdSuivi(Suivi $id_suivi): self
    {
        $this->id_suivi = $id_suivi;

        return $this;
    }

    public function getIdContact(): ?Contact
    {
        return $this->id_contact;
    }

    public function setIdContact(?Contact $id_contact): self
    {
        $this->id_contact = $id_contact;

        return $this;
    }
}

src/Entity/Suivi.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SuiviRepository")
 */
class Suivi
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Contact", inversedBy="suivis")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_contact;

    /**
     * @ORM\Column(type="date")
     */
    private $date_creation;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TypeSuivi")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_type;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Rappel", mappedBy="id_suivi", cascade={"persist", "remove"})
     */
    private $rappel;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdContact(): ?Contact
    {
        return $this->id_contact;
    }

    public function setIdContact(?Contact $id_contact): self
    {
        $this->id_contact = $id_contact;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getIdType(): ?TypeSuivi
    {
        return $this->id_type;
    }

    public function setIdType(?TypeSuivi $id_type): self
    {
        $this->id_type = $id_type;

        return $this;
    }

    public function getRappel(): ?Rappel
    {
        return $this->rappel;
    }

    public function setRappel(Rappel $rappel): self
    {
        $this->rappel = $rappel;

        // set the owning side of the relation if necessary
        if ($this !== $rappel->getIdSuivi()) {
            $rappel->setIdSuivi($this);
        }

        return $this;
    }
}

src/Form/SuiviType.php
<?php

namespace App\Form;

use App\Entity\Suivi;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SuiviType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('description',TextareaType::class,['label'=>'Description','attr'=>['class'=>'form-control']])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Suivi::class,
        ]);
    }
}

src/Controller/SuiviController.php
<?php

namespace App\Controller;

use App\Entity\Suivi;
use App\Entity\Rappel;
use App\Form\SuiviType;
use App\Repository\SuiviRepository;
use App\Repository\ContactRepository;
use App\Repository\TypeSuiviRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/suivi")
 */
class SuiviController extends AbstractController
    {
    /**
     * @Route("/index/{page}", name="suivi_index")
     */
    public function index(SuiviRepository $suiviRepository,int $page=1): Response
        {/*Calcul le nombre de pages par le nombre total de sessions divisé par 10
        Cette variable doit rester en float pour le template twig correspondant*/
        $pages=count($suiviRepository->findAll())/10;
        //Vérifie que la valeur de l'argument $page est bien compris entre 1 et $pages
        $page=($page>=1&&$page<=(int)$pages)?$page:1;
        //Récupére jusqu'a 10 sessions, et selon la page
        $suivis=$suiviRepository->findBy([],null,10,($page*10)-10);
        /*Si il y a au moins 4 pages qui précède la page actuelle
        Alors la pagination commence avec le numéro de la page actuelle - 4
        Sinon, elle commence à la page 1*/
        $pageDebut=($page-4>=1)?$page-4:1;
        /*Si il y a plus de 4 pages qui suit la page actuelle
        Alors la pagination s'arrête avec le numéro de la page actuelle + 4
        Sinon, elle s'arrête à la dernière page*/
        $pageFin=($page+4<=(int)$pages)?$page+4:(int)$pages;
        return $this->render('suivi/index.html.twig', [
            'controller_name'=>'suivi',
            'suivis'=>$suivis,
            'pageDebut'=>$pageDebut,
            'pageFin'=>$pageFin,
            'page'=>$page,
            'pages'=>$pages
            ]);
        }

    /**
     * @Route("/new", name="suivi_new", methods={"GET","POST"})
     */
    public function new(Request $request,ContactRepository $contactRepository,TypeSuiviRepository $typeSuiviRepository): Response
        {
        $suivi = new Suivi();
        $form = $this->createForm(SuiviType::class, $suivi);
        $form->handleRequest($request);
        //Vérification si un contact et un type de suivi à été selectionné
        if($form->isSubmitted()&&$form->isValid()&&isset($request->get("contact")['id'])&&isset($request->get("type_suivi")['id'])) 
            {
            $entityManager = $this->getDoctrine()->getManager();
            //Ajout des données au suivi
            $suivi->setIdContact($contactRepository->find($request->get("contact")['id']));
            $suivi->setDateCreation(new \DateTime());
            $suivi->setIdType($typeSuiviRepository->find($request->get("type_suivi")['id']));
            //Vérification de si il y a eu des données pour un rappel
            if(isset($request->get("rappel")["date_rappel"])&&isset($request->get("rappel")["description"])&&isset($request->get("rappel")["valide"]))
                {//Création et persistance du rappel
                $rappel=new Rappel();
                $rappel->setDateRappel(new \DateTime($request->get("rappel")["date_rappel"]));
                $rappel->setDescription($request->get("rappel")["description"]);
                $rappel->setValide((bool)$request->get("rappel")["valide"]);
                $rappel->setIdSuivi($suivi);
                $rappel->setIdContact($contactRepository->find($request->get("contact")['id']));
                $entityManager->persist($rappel);
                }
            //Sauvegarde du suivi en base de données
            $entityManager->persist($suivi);
            $entityManager->flush();
            //Redirection vers le détail du suivi
            return $this->redirectToRoute('suivi_show',['id' => $suivi->getId()]);
            }

        return $this->render('suivi/new.html.twig', [
            'controller_name'=>'suivi',
            'suivi' => $suivi,
            'contacts'=>$contactRepository->findAll(),
            'typeSuivis'=>$typeSuiviRepository->findAll(),
            'form' => $form->createView(),
            ]);
        }

    /**
     * @Route("/{id}", name="suivi_show", methods={"GET"})
     */
    public function show(Suivi $suivi): Response
        {
        return $this->render('suivi/show.html.twig', [
            'controller_name'=>'suivi',
            'suivi' => $suivi,
            ]);
        }

    /**
     * @Route("/{id}/edit", name="suivi_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Suivi $suivi,ContactRepository $contactRepository,TypeSuiviRepository $typeSuiviRepository): Response
        {
        $form = $this->createForm(SuiviType::class, $suivi);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) 
            {//Modification des données du suivi
            if(isset($request->get("contact")['id']))$suivi->setIdContact($contactRepository->find($request->get("contact")['id']));
            if(isset($request->get("type_suivi")['id']))$suivi->setIdType($typeSuiviRepository->find($request->get("type_suivi")['id']));
            //Si le suivi n'a pas de rappel et qu'il y a un envoie des données pour un rappel
            if(isset($request->get("rappel")["date_rappel"])&&isset($request->get("rappel")["description"])&&isset($request->get("rappel")["valide"])&&!$suivi->getRappel())
                {//Création d'un rappel et persistance en base de données
                $rappel=new Rappel();
                $rappel->setDateRappel(new \DateTime($request->get("rappel")["date_rappel"]));
                $rappel->setDescription($request->get("rappel")["description"]);
                $rappel->setValide((bool)$request->get("rappel")["valide"]);
                $rappel->setIdSuivi($suivi);
                $rappel->setIdContact($contactRepository->find($request->get("contact")['id']));
                $this->getDoctrine()->getManager()->persist($rappel);
                }
            else
                {//Sinon, modification du rappel actuelle
                if(isset($request->get("rappel")["date_rappel"]))$suivi->getRappel()->setDateRappel(new \DateTime($request->get("rappel")["date_rappel"]));
                if(isset($request->get("rappel")["description"]))$suivi->getRappel()->setDescription($request->get("rappel")["description"]);
                if(isset($request->get("rappel")["valide"]))$suivi->getRappel()->setValide((bool)$request->get("rappel")["valide"]);
                }
            //Sauvegarde en base de données
            $this->getDoctrine()->getManager()->flush();
            //Redirection vers le détail du suivi
            return $this->redirectToRoute('suivi_show', ['id' => $suivi->getId()]);
            }

        return $this->render('suivi/edit.html.twig', [
            'controller_name'=>'suivi',
            'suivi' => $suivi,
            'contacts'=>$contactRepository->findAll(),
            'typeSuivis'=>$typeSuiviRepository->findAll(),
            'form' => $form->createView(),
            ]);
        }

    /**
     * @Route("/{id}", name="suivi_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Suivi $suivi): Response
        {
        if($this->isCsrfTokenValid('delete'.$suivi->getId(), $request->request->get('_token')))
            {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($suivi);
            $entityManager->flush();
            }

        return $this->redirectToRoute('suivi_index');
        }

    /**
     * @Route("/rappel/{id}", name="suivi_delete_rappel", methods={"POST"})
     */
    public function deleteRappel(Request $request, Suivi $suivi): Response
        {
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($suivi->getRappel());
        $entityManager->flush();

        return $this->redirectToRoute('suivi_index');
        }
    }

templates/suivi/_delete_form.html.twig
<form method="post" action="{{ path('suivi_delete', {'id': suivi.id}) }}" onsubmit="return confirm('Est-vous sûr de supprimer ce suivi ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ suivi.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/suivi/_form.html.twig
{{ form_start(form,{'attr':{'class':'container-fluid'}}) }}
<div class="d-flex">
	<a href="{{ path('suivi_index') }}" class="btn btn-primary">Retour à la liste</a>
	{% if suivi.id is not null %}
      <a href="{{ path('suivi_show', {'id': suivi.id}) }}" class="btn btn-primary ml-2">Afficher</a>
  {% endif %}
	<button class="btn btn-success ml-2">{{ button_label|default('Sauvegarder') }}</button>
</div>
<div class="row">
	<div class="col-auto mb-3">
		<h4 class="text-light">Suivi</h4>
		<div class="input-group mb-1">
			<div class="input-group-prepend"><label for="type_suivi_id" class="required input-group-text">Type de suivi</label></div>
			<select id="type_suivi_id" class="form-control" name="type_suivi[id]" required>
          {% for typeSuivi in typeSuivis %}
              <option value="{{ typeSuivi.id }}" {% if suivi.idType == typeSuivi %}selected{% endif %}>{{ typeSuivi.libelle }}</option>
          {% endfor %}
      </select>
		</div>
		<div class="input-group mb-1">
			<div class="input-group-prepend"><label for="contact_id" class="required input-group-text">Contact</label></div>
			<select class="form-control" id="contact_id" name="contact[id]" required>
          {% for contact in contacts %}
              <option value="{{ contact.id }}" {% if suivi.idContact == contact %}selected{% endif %}>{{ contact.prenom~" "~contact.nom }}</option>
          {% endfor %}
      </select>
		</div>
		<div class="form-group">
    	{{ form_label(form.description,'',{'label_attr':{'class':'input-group-text'}}) }}
			{{ form_widget(form.description,{'attr':{'class':'form-control'}}) }}
    </div>
	</div>
	<div class="col-auto">
		<div class="d-flex align-items-center">
			<h4 class="text-light">Rappel {% if suivi.id is null %}(non obligatoire){% endif %}</h4>
			{% if suivi.rappel.id is defined %}
					<button type="button" id="btnSuppressionRappel" class="btn btn-danger m-1" onclick="suppressionRappel({{ suivi.id }})">Supprimer le rappel</button>
			{% endif %}
		</div>
		<div class="input-group mb-1">
			<div class="input-group-prepend"><label for="rappel_date_rappel" class="required input-group-text">Date de rappel</label></div>
			<input id="rappel_date_rappel" class="form-control" type="date" name="rappel[date_rappel]" {% if suivi.rappel.dateRappel is defined %}value="{{ suivi.rappel.dateRappel.format('Y-m-d') }}"{% endif %}>
		</div>
		<div class="input-group mb-1">
			<label class="required input-group-text mr-1">Valide</label>
			<div class="d-flex align-items-center">
				<div class="form-check">
					<input id="rappel_valide_oui" type="radio" name="rappel[valide]" value="1" {% if suivi.rappel.valide is defined and suivi.rappel.valide == true %}checked{% endif %} class="form-check-input">
					<label for="rappel_valide_oui" class="form-check-label mb-0 mr-2 text-light">Oui</label>
				</div>
				<div class="form-check">
					<input id="rappel_valide_non" type="radio" name="rappel[valide]" value="0" {% if suivi.rappel.valide is defined and suivi.rappel.valide == false %}checked{% endif %} class="form-check-input">
					<label for="rappel_valide_non" class="form-check-label mb-0 mr-2 text-light">Non</label>
				</div>
			</div>
		</div>
		<div class="form-group mb-1">
			<label for="rappel_description" class="required input-group-text">Description</label>
      <textarea id="rappel_description" class="form-control" name="rappel[description]">{% if suivi.rappel.description is defined %}{{ suivi.rappel.description }}{% endif %}</textarea>
		</div>
	</div>
</div>
{{ form_end(form) }}

templates/suivi/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() ~ " - Editier Suivi" }}{% endblock %}

{% block body %}
{{ include('suivi/_form.html.twig') }}
{% endblock %}

{% block javascripts %}
{{ parent() }}
<script type="text/javascript">
function suppressionRappel(id)
    {
    $.ajax({
        url:"{{ path('suivi_delete_rappel',{'id':'id'}) }}".replace('id',id),
        type:"POST",
        dataType:"html",
        data:{},
        async:true,
        success:function(data)
            {
            $('#rappel_date_rappel').val('');
            $('#rappel_description').val('');
            $('#rappel_valide_oui').removeAttr('checked');
            $('#rappel_valide_non').removeAttr('checked');
            $('#btnSuppressionRappel').remove();
            }
        });
    }
</script>
{% endblock %}

templates/suivi/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() ~ " - Suivis commerciaux" }}{% endblock %}

{% block body %}
<div class="container-fluid">
  <h3 class="text-light">Liste des suivis commerciaux</h3>
  <a href="{{ path('suivi_new') }}" class="btn btn-primary mb-2">Nouveau suivi commercial</a>
  {% if pages > 1 %}
      <nav class="d-flex">
          <ul class="pagination">
              {% if page > 1 %}
                  <li class="page-item"><a class="page-link" href="{{ path('suivi_index', {'page': 1}) }}">Début</a></li>
                  <li class="page-item"><a class="page-link" href="{{ path('suivi_index', {'page': page-1}) }}">Précédent</a></li>
              {% endif %}
              {% for i in range(pageDebut,pageFin) %}
                  <li class="page-item">
                      {% if page == i %}
                          <a class="page-link bg-primary text-light">{{ i }}</a>
                      {% else %}
                          <a class="page-link" href="{{ path('suivi_index', {'page': i}) }}">{{ i }}</a>
                      {% endif %}
                  </li>
              {% endfor %}
              {% if page < pages %}
                  <li class="page-item"><a class="page-link" href="{{ path('suivi_index', {'page': page+1}) }}">Suivant</a></li>
                  <li class="page-item"><a class="page-link" href="{{ path('suivi_index', {'page': pages}) }}">Fin</a></li>
              {% endif %}
          </ul>
      </nav>
  {% endif %}
  <div class="table-responsive">
    <table class="table table-dark table-striped table-bordered mb-0">
        <thead>
            <tr>
                <th class="text-truncate">Date de création</th>
                <th class="text-truncate">Description</th>
                <th class="text-truncate">Contact</th>
                <th class="w-25">Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for suivi in suivis %}
            <tr>
                <td class="align-middle text-truncate">{{ suivi.dateCreation ? suivi.dateCreation|date('Y-m-d') : '' }}</td>
                <td class="align-middle text-truncate">{{ suivi.description }}</td>
                <td class="align-middle text-truncate">{{ suivi.idContact.prenom~" "~suivi.idContact.nom }}</td>
                <td>
                  <div class="d-flex">
                    <a href="{{ path('suivi_show', {'id': suivi.id}) }}" class="btn btn-primary">Afficher</a>
                    <a href="{{ path('suivi_edit', {'id': suivi.id}) }}" class="btn btn-warning ml-2 mr-2">Editer</a>
                    {{ include('suivi/_delete_form.html.twig') }}
                  </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Aucun suivi commercial</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
  </div>
</div>
{% endblock %}

templates/suivi/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() ~ " - Nouvelle Formation" }}{% endblock %}

{% block body %}
{{ include('suivi/_form.html.twig') }}
{% endblock %}

templates/suivi/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ parent() ~ " - Affichage Suivi" }}{% endblock %}

{% block body %}
<div class="container-fluid">
  <div class="d-flex">
      <a href="{{ path('suivi_index') }}" class="btn btn-primary">Retour à la liste</a>
      <a href="{{ path('suivi_edit', {'id': suivi.id}) }}" class="btn btn-warning ml-2 mr-2">Editier</a>
      {{ include('suivi/_delete_form.html.twig') }}
  </div>
  <div class="row">
    <div class="col-auto mb-3">
      <h4 class="text-light">Suivi</h4>
      <p class="text-light mb-1">
          <strong class="text-white">Date de création: </strong>
          {{ suivi.dateCreation|date('Y-m-d') }}
      </p>
      <p class="text-light mb-1">
          <strong class="text-white">Description: </strong>
          {{ suivi.description }}
      </p>
      <p class="text-light mb-1">
          <strong class="text-white">Type de suivi: </strong>
          {{ suivi.idType.libelle }}
      </p>
      <p class="text-light mb-0 align-items-center">
          <strong class="text-white">Contact: </strong>
          {{ suivi.idContact.prenom~" "~suivi.idContact.nom~" " }}
          <button type="button" class="btn btn-info" data-toggle="modal" data-target="#modalContact" onclick="detailsContact({{ suivi.idContact.id }})">Détails</button>
      </p>
    </div>
    {% if suivi.rappel is not null %}
      <div class="col-auto">
          <h4 class="text-light">Rappel</h4>
          <p class="text-light mb-1">
              <strong class="text-white">Date de rappel: </strong>
              {{ suivi.rappel.dateRappel|date('Y-m-d') }}
          </p>
          <p class="text-light mb-1">
              <strong class="text-white">Description: </strong>
              {{ suivi.rappel.description }}
          </p>
          <p class="text-light mb-0">
              <strong class="text-white">valide: </strong>
              {{ suivi.rappel.valide ? "oui":"non" }}
          </p>
      </div>
    {% endif %}
  </div>
</div>

<!--Modal-->
<div class="modal fade" id="modalContact" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Contact</h5>
            </div>
            <div class="modal-body bg-secondary w-100" id="modal-body-contact">
                <p class="text-center text-light m-0">Chargement des données, veuillez patientez ....</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascripts %}
{{ parent() }}
<script type="text/javascript">
function detailsContact(id)
    {
    var path="{{ path('contact_show',{'id':'id'}) }}"
    path=path.replace('id',id);
    $.ajax({
        url:path,
        type:"POST",
        dataType:"html",
        data:{},
        async:true,
        success:function(data)
            {
            $('#modal-body-contact').html(data);
            }
        });
    }
</script>
{% endblock %}